name: Build STM32CubeIDE Project
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Generate Debug build folder
        run: mkdir -p Debug
      
      - name: Setup virtual display (for JVM stability)
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          export DISPLAY=:99
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          sleep 2
  
      - name: Build STM32CubeIDE project (Debug)
        env:
          DISPLAY: :99
        uses: xanderhendriks/action-build-stm32cubeide@v15.0
        with:
          project-path: '.'
          project-target: 'foc_drv8323_g4'
          # Add JVM options to prevent crashes
          build-configuration: 'Debug'
          # The action might not support custom JVM args directly, so we'll handle crashes in post-build
        continue-on-error: true  # Allow JVM crash but continue workflow
      
      - name: Verify build success despite JVM crash
        run: |
          if [ -f "Debug/foc_drv8323_g4.elf" ] || [ -f "foc_drv8323_g4.elf" ]; then
            echo "✅ Build successful - ELF file found"
            # Move files to Debug folder if they're in root
            if [ -f "foc_drv8323_g4.elf" ] && [ ! -f "Debug/foc_drv8323_g4.elf" ]; then
              mv foc_drv8323_g4.* Debug/ 2>/dev/null || true
            fi
            ls -la Debug/
            exit 0
          else
            echo "❌ Build failed - No ELF file found"
            ls -la
            exit 1
          fi
      
      - name: Generate additional build artifacts
        run: |
          cd Debug
          if [ -f "foc_drv8323_g4.elf" ]; then
            # Generate binary file if it doesn't exist
            if [ ! -f "foc_drv8323_g4.bin" ]; then
              arm-none-eabi-objcopy -O binary foc_drv8323_g4.elf foc_drv8323_g4.bin
            fi
            # Generate hex file
            if [ ! -f "foc_drv8323_g4.hex" ]; then
              arm-none-eabi-objcopy -O ihex foc_drv8323_g4.elf foc_drv8323_g4.hex
            fi
            # Show file sizes
            arm-none-eabi-size foc_drv8323_g4.elf
            ls -la
          fi
        continue-on-error: true
      
      - name: Upload built binaries
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            Debug/*.elf
            Debug/*.bin
            Debug/*.hex
            Debug/*.map
            Debug/*.list
